app:
    name: app
    debug: true
    url: http://localhost:8080

db:
    host: localhost
    name: table
    user: user
    password: password

twig:
    templateDir: /resources/views
    cacheDir: /storage/twig/cache
    debug: true
